# -*- coding: utf-8 -*-
"""health care.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqL807Us4T2DBYOj7ozmfA-sCLSVxpF4
"""

import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px

df= pd.read_csv("heart.csv")

df.head()

df.info()

df.columns

df.shape

df.isnull().sum()

df.duplicated().sum()

df.dtypes

# Summary statistics for numerical columns
df.describe()

"""**Heart Disease Distribution**"""

import matplotlib.pyplot as plt
sns.countplot(x="HeartDisease",data=df)
plt.xlabel("Heart Disease")
plt.ylabel("Patient Count")
plt.title("heart disease distribution")
plt.show()

"""**Distribution of Patients by Gender**"""

sns.countplot(x="Sex",data=df)
plt.xlabel("Gender")
plt.ylabel("Patient Count")
plt.title("Distribution of Patients by Gender")
plt.show()

"""**Distribution of patients by Age**


"""

import matplotlib.pyplot as plt
import seaborn as sns
sns.histplot(df["Age"],bins=20,kde=True)
plt.xlabel("Age (Years)")
plt.ylabel("Patient Count")
plt.title("Distribution of patients by Age")
plt.show()

"""**Relationship Between Age and Maximum Heart Rate by Heart Disease Status**"""

sns.scatterplot(x="Age",y="MaxHR",hue="HeartDisease",data=df)
plt.title("Relationship Between Age and MaxHR by Heart Disease Status")
plt.show()

"""**Age Distribution by Heart Disease Status**"""

sns.boxplot(x="HeartDisease",y="Age",data=df)
plt.title("Age Distribution by Heart Disease Status")
plt.show()

"""**Distribution of Chest Pain Types**"""

df["ChestPainType"].value_counts().plot(kind="bar")
plt.title("Distribution of Chest Pain Types")
plt.xlabel("Chest Pain Type")
plt.ylabel("Patient Count")
plt.show()

"""**Distribution of ST Segment Slope Types**"""

df["ST_Slope"].value_counts().plot(kind="bar")
plt.title("Distribution of ST Segment Slope Types")
plt.xlabel("ST Segment Slope")
plt.ylabel("Patient Count")
plt.show()

"""**Fasting Blood Sugar by Heart Disease Status**"""

sns.countplot(x="FastingBS",hue="HeartDisease", data=df)
plt.title("Fasting Blood Sugar by Heart Disease Status")
plt.show()

"""**Relationship Between Age and Cholesterol Levels**"""

sns.regplot(x="Age", y="Cholesterol", data=df,scatter_kws={"alpha":0.6},line_kws={"color": "red"})
plt.title("Relationship Between Age and Cholesterol Levels")
plt.show()

"""**Correlation Heatmap b/w Age, MaxHR, oldpeak, HeartDisease**"""

sns.heatmap(df[["Age","MaxHR","Oldpeak","HeartDisease"]].corr(),annot=True,cmap="Reds")
plt.title("Correlation Heatmap of Selected Heart Disease Features")
plt.show()

"""**Pairwise Relationships Among Selected Heart Disease Features**"""

top_features = ["Age","MaxHR", "Oldpeak","HeartDisease"]
sns.pairplot(df[top_features],hue="HeartDisease")
plt.show()

"""CONCLUSION:

1. Heart disease patients are generally older.

2. Higher Oldpeak is associated with heart disease.

3. Maximum Heart Rate tends to be lower among heart disease patients.

4. Chest Pain Type is a strong predictor.

5. Fasting Blood Sugar shows only a weak relationship.

6. Cholesterol alone is not a strong indicator.
"""